services:
  backend:
    build: ./backend
    container_name: ironic-backend
    restart: always
    env_file:
      - ./backend/.env.docker
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app        # Mount local code into container
      - /app/node_modules     # Prevent node_modules overwrite
    command: npm run start:dev

  ml:
    build: ./ml
    container_name: ironic-ml
    restart: always
    env_file:
      - ./ml/.env.docker 
    ports:
      - "8000:8000"
    volumes:
      - ./ml:/app  # Mount your local ml code into the container
