# docker-compose.yml
version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: ironic-db
    restart: always
    environment:
      POSTGRES_USER: ironicuser
      POSTGRES_PASSWORD: ironicpass
      POSTGRES_DB: ironicdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build: ./backend
    container_name: ironic-backend
    restart: always
    depends_on:
      - postgres
    environment:
    env_file:
      - ./backend/.env.docker 
    ports:
      - "3000:3000"

  ml:
    build: ./ml
    container_name: ironic-ml
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - ./ml/.env.docker 

volumes:
  pgdata: